# 00. PyTorch Fundamentals Exercises

### 1. Documentation reading

A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness):
  * The documentation on [`torch.Tensor`](https://pytorch.org/docs/stable/tensors.html#torch-tensor).
  * The documentation on [`torch.cuda`](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).



In [ ]:
# No code solution (reading)

### 2. Create a random tensor with shape `(7, 7)`.


In [2]:
# Import torch
import torch

# Create random tensor
tensor_A = torch.rand(size=(7,7))
tensor_A


tensor([[0.7324, 0.6500, 0.1367, 0.8817, 0.2998, 0.9197, 0.9383],
        [0.4563, 0.0932, 0.0843, 0.9527, 0.8305, 0.3193, 0.0777],
        [0.1906, 0.3379, 0.8839, 0.4537, 0.7868, 0.9801, 0.9552],
        [0.9505, 0.2318, 0.5551, 0.3782, 0.0547, 0.3979, 0.6419],
        [0.0924, 0.5427, 0.9467, 0.4765, 0.1426, 0.3878, 0.0553],
        [0.9027, 0.1875, 0.3094, 0.7981, 0.2382, 0.0488, 0.2443],
        [0.9352, 0.1556, 0.9514, 0.7044, 0.8160, 0.4422, 0.8519]])

### 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with shape `(1, 7)` (hint: you may have to transpose the second tensor).

In [6]:
# Create another random tensor
tensor_B = torch.rand(1,7)
tensor_B
# Perform matrix multiplication
tensor_C = torch.mm(tensor_A, tensor_B.T)
tensor_C


tensor([[2.7744],
        [1.4706],
        [2.7921],
        [2.2148],
        [1.5995],
        [1.7633],
        [3.2062]])

### 4. Set the random seed to `0` and do 2 & 3 over again.

The output should be:
```
(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]), torch.Size([7, 1]))
```

In [9]:
# Set manual seed
RANDOM_SEED = 0
# Create two random tensors
torch.manual_seed(RANDOM_SEED)
x = torch.rand(size=(7,7))

#torch.manual_seed(RANDOM_SEED)
y = torch.rand(size=(1,7))

# Matrix multiply tensors
z= torch.matmul(x, y.T)
z, z.shape




(tensor([[1.8542],
         [1.9611],
         [2.2884],
         [3.0481],
         [1.7067],
         [2.5290],
         [1.7989]]),
 torch.Size([7, 1]))

### 5. Speaking of random seeds, we saw how to set it with `torch.manual_seed()` but is there a GPU equivalent? (hint: you'll need to look into the documentation for `torch.cuda` for this one)
  * If there is, set the GPU random seed to `1234`.

In [ ]:
# Set random seed on the GPU
RANDOM_SEED = 1234
torch.cuda.manual_seed(RANDOM_SEED)


### 6. Create two random tensors of shape `(2, 3)` and send them both to the GPU (you'll need access to a GPU for this). Set `torch.manual_seed(1234)` when creating the tensors (this doesn't have to be the GPU random seed). The output should be something like:

```
Device: cuda
(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))
```

In [11]:
# Set random seed
torch.manual_seed(1234)

# Check for access to GPU
device = "cuda" if torch.cuda.is_available() else "cpu"

# Create two random tensors on GPU
X = torch.rand(2, 3).to(device)
Y = torch.rand(2, 3).to(device)
X, Y

(tensor([[0.0290, 0.4019, 0.2598],
         [0.3666, 0.0583, 0.7006]], device='cuda:0'),
 tensor([[0.0518, 0.4681, 0.6738],
         [0.3315, 0.7837, 0.5631]], device='cuda:0'))


### 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

The output should look like:
```
(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'), torch.Size([2, 2]))
```

In [13]:
# Perform matmul on tensor_A and tensor_B
Z = torch.mm(X, Y.T)
Z, Z.shape

(tensor([[0.3647, 0.4709],
         [0.5184, 0.5617]], device='cuda:0'),
 torch.Size([2, 2]))

### 8. Find the maximum and minimum values of the output of 7.

In [23]:
# Find max
Z_max = Z.max()
# Find min
Z_min = Z.min()
# torch.argmin(Z)
Z_min, Z_max

(tensor(0.3647, device='cuda:0'), tensor(0.5617, device='cuda:0'))

### 9. Find the maximum and minimum index values of the output of 7.

In [24]:
from ast import arg
# Z = Z.flatten()

# # Find arg max
# Z_mxv = Z[Z_max.item()]

# # Find arg min
# Z_mnv = Z[Z_min.item()]
# Z_mxv, Z_mnv


argm = Z.argmax()
argmn = Z.argmin()
argm, argmn

(tensor(3, device='cuda:0'), tensor(0, device='cuda:0'))


### 10. Make a random tensor with shape `(1, 1, 1, 10)` and then create a new tensor with all the `1` dimensions removed to be left with a tensor of shape `(10)`. Set the seed to `7` when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

The output should look like:

```
tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
```

In [26]:
# Set seed
RANDOM_SEED = 7
torch.manual_seed(RANDOM_SEED)
# Create random tensor
R = torch.rand(size=(1,1,1,10))

# Remove single dimensions
R_squeezed = R.squeeze()

# Print out tensors and their shapes
print(R, R.shape)
print(R_squeezed, R_squeezed.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])
tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513]) torch.Size([10])
